version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
  
  createbuckets:
    image: minio/mc:RELEASE.2023-10-24T21-42-22Z.hotfix.75d18600
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      exit 0;
      "