spring:
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 123MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  docker:
    compose:
      stop:
        command: stop
application:
  security:
    jwt:
      secret-key: ${SPRING_APPLICATION_SECURITY_JWT_SECRETKEY}
  minio:
    url: ${SPRING_APPLICATION_MINIO_URL}
    accessKey: ${SPRING_APPLICATION_MINIO_ACCESSKEY}
    secretKey: ${SPRING_APPLICATION_MINIO_SECRETKEY}
    bucketName: ${SPRING_APPLICATION_MINIO_BUCKETNAME}